- src/environments/TicTacToe.jl
> do not precompile TicTacToe

- Project.toml
- notebooks/Manifest.toml
- src/ReinforcementLearningAnIntroduction.jl
> Move `extract_experience` from RLCore here

- Manifest.toml
remove `path = "../ReinforcementLearningBase.jl"` in Manifest.toml.
> regenerate Manifest.toml

- notebooks/Chapter05_Blackjack.jl
- notebooks/Chapter05_Left_Right.jl
Fixes https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/issues/42.
> Chapter05 - Multiple definitions for struct

- notebooks/Chapter01_Tic_Tac_Toe.jl
Hi Mates,
Some minor changes to comments.
Keep it up!
> Minor Amendments

- notebooks/Chapter06_Cliff_Walking.jl
- notebooks/Chapter06_Maximization_Bias.jl
This PR fixes the same problem as https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/issues/42 & https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/pull/43 but for Chapter06.
> Chapter06 - Multiple definitions errors

- notebooks/Chapter07_Random_Walk.jl
This PR fixes the same problems as https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/pull/51 but for Chapter07.
>  Chapter07 - Multiple definitions errors

- notebooks/Chapter06_Cliff_Walking.jl
- notebooks/Chapter06_Maximization_Bias.jl
- notebooks/Chapter07_Random_Walk.jl
Small PR to add `x` & `y` labels on some plots.
Also changed `y` label on Chapter06 Maximization Bias plot to percents like in the book.
> Add x & y labels on plots

- notebooks/Chapter08_Expectation_VS_Sample.jl
- notebooks/Chapter08_Maze.jl
This PR fixes the same problems as https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/pull/52 but for Chapter08.
> Chapter08 - fix multiple assignment error

- notebooks/Chapter08_Expectation_VS_Sample.jl
- notebooks/Chapter08_Maze.jl
- notebooks/Chapter08_Trajectory_Sampling.jl
Small PR that mainly add some labels on plots and some titles in notebook `Chapter08_Expectation_VS_Sample.jl`.
> Small changes on Chapter08

- README.md
fix new ReinforcementLearningZoo link and add exercises repo link
> fix link and add exercises repo link

- notebooks/Chapter09_Random_Walk.jl
This PR includes the following changes on `Chapter09_Random_Walk.jl` notebook:
- Fix multiple definitions in Pluto
- Add x & y labels on plots
- Fix API change: `StateOverriddenEnv` -> `StateTransformedEnv`
- Fix right margin bug in Figure 9.1
> Multiple refactoring in `Chapter09_Random_Walk.jl` notebook

- Manifest.toml
- Project.toml
- notebooks/Chapter12_Random_Walk.jl
- notebooks/Chapter13_Short_Corridor.jl
This PR add some plot labels to chap12&13 notebooks.
To be noted: I added `Pluto` and `LaTeXStrings` to the `Project.toml`.
> Small changes to chap12&13 notebooks

- .github/workflows/ExportPluto.yaml
- notebooks/Chapter02_Ten_Armed_Testbed.jl
> Export static html version of notebooks

- Manifest.toml
- notebooks/Chapter09_Random_Walk.jl
Apparently https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/issues/73 was just a cell issue in Pluto.
> Fix cyclic references

- .github/workflows/ExportPluto.yaml
This PR bumps Julia version to 1.7 in CI.
> Try to fix HTML static export for notebooks

- README.md
Need to activate and instantiate, as well as no need to install pluto since it is already in the environment.
> Clarify install/startup in readme

- notebooks/Chapter01_Tic_Tac_Toe.jl
Update link to run function, fixes #55 .
> Update link to run function

- notebooks/Chapter02_Ten_Armed_Testbed.jl
no difference between the two ultimately since it's a one-step problem, but `TDLearner` was not mentioned before whereas `MonteCarloLearner` was introduced in the first notebook.  also the way the book presented the algorithm would imply that it's meant as a MC algorithm.
> changed learner type for clarity

- notebooks/Chapter09_Random_Walk.jl
fixed plot labels that were on the opposite sides
> Fix chap9 label

- notebooks/Chapter07_Random_Walk.jl
- notebooks/Chapter09_Random_Walk.jl
in my testing, there is a performance speedup of 6 times
> improved performance of figure 9.10

- notebooks/Chapter07_Random_Walk.jl
- notebooks/Chapter13_Short_Corridor.jl
closes #68 
learning happens from the end of the episode, in accordance with the original implementation
> implemented figure 13.2
